-- Owner: Track 1 (Foundation, Auth, and API infrastructure)
-- Responsible for: initial schema baseline, hand-maintained to describe intent alongside backend/prisma/schema.prisma
-- (the actual source of truth going forward).
--
-- Prisma migrate workflow note: once the team runs `npx prisma migrate dev --name init` against schema.prisma,
-- Prisma generates its own timestamped SQL migration files under backend/prisma/migrations/ and this hand-written
-- file is superseded — keep it only as a readable scaffold sketch until that first `prisma migrate dev` run,
-- then either delete it or keep it as a historical reference (do not hand-edit it after Prisma migrations exist).

-- TODO: CREATE TABLE users (id, email, password_hash, password_salt, name, avatar, oauth_provider, oauth_id, created_at, updated_at)
-- TODO: CREATE TABLE projects (id, name, owner_id, created_at, updated_at)
-- TODO: CREATE TABLE project_members (project_id, user_id, role) with a composite primary key / unique constraint
-- TODO: CREATE TABLE project_invites (id, project_id, token_hash unique, role, max_uses nullable, use_count default 0,
--       expires_at nullable, created_by, created_at, revoked_by nullable FK users.id, revoked_at nullable) —
--       token_hash stores a hash of the invite token, never the plaintext; project_members stays the sole
--       authorization source of truth, invites only gate the one-time join action
-- TODO: CREATE TABLE boards, lists, cards with foreign keys down to projects/boards/lists
-- TODO: CREATE TABLE notes (id, project_id, content_json, updated_by, updated_at)
-- TODO: CREATE TABLE attachments (id, project_id, card_id nullable, file_url, file_type, uploaded_by, uploaded_at)
-- TODO: CREATE TABLE git_links (card_id, repo_url, branch_name, pr_status)
-- TODO: CREATE TABLE notifications (id, user_id, type, payload, read_at, created_at)
-- TODO: CREATE TABLE webhook_events (id, provider, repo, event_type, payload, processed_at, created_at)
-- TODO: CREATE TABLE api_keys (id, project_id nullable, user_id nullable, key_hash, rate_limit, created_at)
-- TODO: add foreign key constraints and indexes matching docs/db-schema.md and backend/prisma/schema.prisma
